language: objective-c
osx_image: xcode9.2
rvm:
- 2.2         #see before_install for getting RVM stable.

env:
- TRAVIS_TAG="Deploy-2019.3.0f6" PROJECT_NAME="TowerDefens" UNITY_PROJECT_PATH="TowerDefens" DEPLOY_UNITYPACKAGE="path set in deploy script"


cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

    
before_install:
- chmod a+x ./Scripts/*.sh

install:
- cat /etc/hosts
- ./Scripts/install.sh

script:
- ./Scripts/build.sh
- ./Scripts/run-tests.sh

after_success:
- ./Scripts/export-unity-package.sh

before_deploy:
- DEPLOY_UNITYPACKAGE="$(ls -a release/*.zip | head -n 1)"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $DEPLOY_UNITYPACKAGE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true 
